Class {
	#name : #ASDEAdresse,
	#superclass : #ASDEEinkaufen,
	#instVars : [
		'bez',
		'str',
		'hsnr',
		'plz',
		'ort',
		'land',
		'tel',
		'bemerkung',
		'userId'
	],
	#category : #'AsdEinkaufen-Core-Model'
}

{ #category : #accessing }
ASDEAdresse >> bemerkung [
	^ bemerkung
]

{ #category : #accessing }
ASDEAdresse >> bemerkung: anObject [
	bemerkung := anObject
]

{ #category : #accessing }
ASDEAdresse >> bez [
	^ bez
]

{ #category : #accessing }
ASDEAdresse >> bez: anObject [
	bez := anObject
]

{ #category : #accessing }
ASDEAdresse >> hsnr [
	^ hsnr
]

{ #category : #accessing }
ASDEAdresse >> hsnr: anObject [
	hsnr := anObject
]

{ #category : #accessing }
ASDEAdresse >> land [
	^ land
]

{ #category : #accessing }
ASDEAdresse >> land: anObject [
	land := anObject
]

{ #category : #accessing }
ASDEAdresse >> ort [
	^ ort
]

{ #category : #accessing }
ASDEAdresse >> ort: anObject [
	ort := anObject
]

{ #category : #accessing }
ASDEAdresse >> plz [
	^ plz
]

{ #category : #accessing }
ASDEAdresse >> plz: anObject [
	plz := anObject
]

{ #category : #accessing }
ASDEAdresse >> str [
	^ str
]

{ #category : #accessing }
ASDEAdresse >> str: anObject [
	str := anObject
]

{ #category : #accessing }
ASDEAdresse >> tel [
	^ tel
]

{ #category : #accessing }
ASDEAdresse >> tel: anObject [
	tel := anObject
]

{ #category : #accessing }
ASDEAdresse >> userId [
	^ userId
]

{ #category : #accessing }
ASDEAdresse >> userId: anObject [
	userId := anObject
]
